/**
 * Sprite definitions for WattWise apartment
 * Generated by Lane B Room Builder
 * Cleaned and validated: 2026-08-29
 *
 * All coordinates are zero-based (col, row)
 * Each sprite defines its source location in the sprite sheet
 */

export interface SpriteDefinition {
  sheet: "interiors" | "roomBuilder";
  col: number;
  row: number;
  width: number;  // in tiles (32px each)
  height: number; // in tiles (32px each)
}

export const TILE_SIZE = 32;

// Sprite sheet paths relative to public/assets/
export const SPRITE_SHEETS = {
  interiors: "interior/32x32/Interiors_free_32x32.png",
  roomBuilder: "interior/32x32/Room_Builder_free_32x32.png",
} as const;

export const spriteMap: Record<string, SpriteDefinition> = {
  floor_middle: {
    sheet: "roomBuilder",
    col: 5,
    row: 11,
    width: 1,
    height: 1,
  },
  something: {
    sheet: "interiors",
    col: 13,
    row: 3,
    width: 1,
    height: 2,
  },
  floor_top: {
    sheet: "roomBuilder",
    col: 0,
    row: 11,
    width: 1,
    height: 1,
  },
  wall: {
    sheet: "roomBuilder",
    col: 1,
    row: 7,
    width: 1,
    height: 2,
  },
  border_topright: {
    sheet: "roomBuilder",
    col: 10,
    row: 1,
    width: 1,
    height: 1,
  },
  border_straight: {
    sheet: "roomBuilder",
    col: 5,
    row: 0,
    width: 1,
    height: 1,
  },
  border_straight_right: {
    sheet: "roomBuilder",
    col: 6,
    row: 0,
    width: 1,
    height: 1,
  },
  border_straight_left: {
    sheet: "roomBuilder",
    col: 7,
    row: 0,
    width: 1,
    height: 1,
  },
  border_topright_real: {
    sheet: "roomBuilder",
    col: 5,
    row: 2,
    width: 1,
    height: 1,
  },
  studytable_chair: {
    sheet: "interiors",
    col: 2,
    row: 38,
    width: 2,
    height: 2,
  },
  socket1: {
    sheet: "interiors",
    col: 1,
    row: 19,
    width: 1,
    height: 1,
  },
  floor2_middle: {
    sheet: "roomBuilder",
    col: 5,
    row: 13,
    width: 1,
    height: 1,
  },
  washroom_floor: {
    sheet: "roomBuilder",
    col: 5,
    row: 9,
    width: 1,
    height: 1,
  },
  mirror: {
    sheet: "interiors",
    col: 3,
    row: 66,
    width: 1,
    height: 2,
  },
  bordertop: {
    sheet: "roomBuilder",
    col: 8,
    row: 1,
    width: 1,
    height: 1,
  },
  shelf: {
    sheet: "interiors",
    col: 4,
    row: 18,
    width: 2,
    height: 3,
  },
  dining_table: {
    sheet: "interiors",
    col: 5,
    row: 10,
    width: 4,
    height: 3,
  },
  table_middle: {
    sheet: "interiors",
    col: 9,
    row: 10,
    width: 1,
    height: 3,
  },
  washroom_wall: {
    sheet: "roomBuilder",
    col: 1,
    row: 9,
    width: 1,
    height: 2,
  },
  sofa_left: {
    sheet: "interiors",
    col: 7,
    row: 72,
    width: 1,
    height: 2,
  },
  sofa_middle: {
    sheet: "interiors",
    col: 9,
    row: 72,
    width: 1,
    height: 2,
  },
  sofa_right: {
    sheet: "interiors",
    col: 8,
    row: 72,
    width: 1,
    height: 2,
  },
  fullsofa_right: {
    sheet: "interiors",
    col: 7,
    row: 80,
    width: 2,
    height: 3,
  },
  window_top: {
    sheet: "interiors",
    col: 0,
    row: 13,
    width: 2,
    height: 1,
  },
  chair_top: {
    sheet: "interiors",
    col: 4,
    row: 21,
    width: 1,
    height: 2,
  },
  chair_left: {
    sheet: "interiors",
    col: 6,
    row: 21,
    width: 1,
    height: 2,
  },
  chair_right: {
    sheet: "interiors",
    col: 7,
    row: 21,
    width: 1,
    height: 2,
  },
  workshelf: {
    sheet: "interiors",
    col: 6,
    row: 18,
    width: 2,
    height: 3,
  },
  bedtop: {
    sheet: "interiors",
    col: 8,
    row: 18,
    width: 2,
    height: 1,
  },
  bedmiddle: {
    sheet: "interiors",
    col: 8,
    row: 16,
    width: 2,
    height: 1,
  },
  bookshelf: {
    sheet: "interiors",
    col: 12,
    row: 71,
    width: 2,
    height: 3,
  },
  tv: {
    sheet: "interiors",
    col: 2,
    row: 24,
    width: 2,
    height: 2,
  },
  fullsofa_left: {
    sheet: "interiors",
    col: 9,
    row: 80,
    width: 2,
    height: 3,
  },
  complete_studytable: {
    sheet: "interiors",
    col: 11,
    row: 35,
    width: 2,
    height: 3,
  },
  door: {
    sheet: "interiors",
    col: 7,
    row: 8,
    width: 1,
    height: 2,
  },
  tv_table: {
    sheet: "interiors",
    col: 5,
    row: 45,
    width: 2,
    height: 1,
  },
  decor_plant: {
    sheet: "interiors",
    col: 12,
    row: 45,
    width: 1,
    height: 2,
  },
  painting: {
    sheet: "interiors",
    col: 8,
    row: 22,
    width: 2,
    height: 2,
  },
  mat: {
    sheet: "interiors",
    col: 10,
    row: 28,
    width: 2,
    height: 2,
  },
  elaborate_window: {
    sheet: "interiors",
    col: 4,
    row: 24,
    width: 3,
    height: 2,
  },
  kitchen_tile: {
    sheet: "roomBuilder",
    col: 11,
    row: 7,
    width: 1,
    height: 1,
  },
  wall_kitchen: {
    sheet: "roomBuilder",
    col: 7,
    row: 9,
    width: 1,
    height: 2,
  },
  bedbottom: {
    sheet: "interiors",
    col: 8,
    row: 19,
    width: 2,
    height: 1,
  },
  entry_carpet: {
    sheet: "interiors",
    col: 13,
    row: 11,
    width: 3,
    height: 2,
  },
  socket_right: {
    sheet: "interiors",
    col: 4,
    row: 29,
    width: 1,
    height: 1,
  }
};

export type SpriteName = keyof typeof spriteMap;
